name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh

    - name: Build and upload release binaries
      run: |
        cargo clean
        cargo build --release --target x86_64-unknown-linux-gnu
        cp target/x86_64-unknown-linux-gnu/release/sui-tx-decode sui-tx-decode_linux

        cargo build --release --target x86_64-pc-windows-gnu
        cp target/x86_64-pc-windows-gnu/release/sui-tx-decode.exe sui-tx-decode_windows.exe

        cargo build --release --target x86_64-apple-darwin
        cp target/x86_64-apple-darwin/release/sui-tx-decode sui-tx-decode_mac

        gh release upload ${{ github.ref }} sui-tx-decode_linux --clobber
        gh release upload ${{ github.ref }} sui-tx-decode_windows.exe --clobber
        gh release upload ${{ github.ref }} sui-tx-decode_mac --clobber
